on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install vcpkg deps
        shell: bash
        run: |
          $VCPKG_INSTALLATION_ROOT/vcpkg.exe install --triplet=x64-windows-static-md xxhash zstd openssl openssl-windows

      - name: Build pijul
        shell: bash
        run: |
          export VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT
          export LIB=$VCPKG_ROOT/installed/x64-windows-static-md/lib
          export OPENSSL_DIR=$VCPKG_ROOT/installed/x64-windows-static-md
          cargo install pijul --version ${{ inputs.version }} --root .

      - uses: actions/upload-artifact@v2
        with:
          name: pijul.exe
          path: bin/pijul.exe
  