on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  VCPKG_DEFAULT_TRIPLET: x64-windows-static-md

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "f6a5d4e8eb7476b8d7fc12a56dff300c1c986131"
          runVcpkgInstall: true

      - name: Build pijul
        shell: bash
        run: |
          export VCPKG_ROOT=./vcpkg
          export LIB=$VCPKG_ROOT/installed/x64-windows-static-md/lib
          export OPENSSL_DIR=$VCPKG_ROOT/installed/x64-windows-static-md
          cargo install pijul --version ${{ inputs.version }} --root . --locked

      - uses: actions/upload-artifact@v2
        with:
          name: pijul.exe
          path: bin/pijul.exe
