name: Test The Setup When It Changes

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      latest-version: ${{ steps.check.outputs.latest-version }}

    steps:
      - uses: actions/checkout@v3
      - id: check
        uses: ./.github/actions/check

  build:
    needs: check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          version: ${{ needs.check.outputs.latest-version }}
