name: Test The Setup When It Changes

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/actions/*/action.yml"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check
        id: check
        uses: ./.github/actions/check
      - name: build
        uses: ./.github/actions/build
        with:
          version: ${{ steps.check.outputs.latest-version }}
