name: Manual Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Pijul version"
        required: true
        default: "~1.0.0-beta"
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ inputs.version }}
