name: Manual Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Pijul version"
        required: true
        default: "~1.0.0-beta"
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        uses: ./.github/actions/build
        with:
          version: ${{ inputs.version }}
      - uses: actions/upload-artifact@v3
        with:
          name: pijul.exe
          path: |
            pijul.exe
            pijul.lock
      - uses: actions/upload-artifact@v3
        with:
          name: pijul-with-git.exe
          path: |
            pijul-with-git.exe
            pijul-with-git.lock
