# This is a basic workflow to help you get started with Actions

name: Build New Releases When Available

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0,12 * * *'
  
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # see if there's a version with no release
  check:
    runs-on: ubuntu-latest
    outputs:
      do-build: ${{ steps.test.outputs.do-build }}
      latest-version: ${{ steps.check.outputs.latest-version }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check
        id: check
        uses: ./.github/actions/check
      - id: test
        run: |
          latest_version="${{ steps.check.outputs.latest-version }}"
          latest_release=$(curl https://api.github.com/repos/boringcactus/pijul-windows-builds/releases/latest | jq -r .tag_name)
          echo "latest-release=$latest_release"
          if [ "$latest_version" != "$latest_release" ]; then
            echo "do-build=yes" | tee -a $GITHUB_OUTPUT
          else
            echo "do-build=no" | tee -a $GITHUB_OUTPUT
          fi

  build:
    runs-on: windows-latest
    needs: check
    if: needs.check.outputs.do-build == 'yes'

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        uses: ./.github/actions/build
        with:
          version: ${{ needs.check.outputs.latest-version }}
      - name: upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: piju*.exe
          file_glob: true
          tag: ${{ needs.check.outputs.latest-version }}
