# This is a basic workflow to help you get started with Actions

name: Build Tags

# Controls when the action will run. 
on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install vcpkg deps
        shell: bash
        run: |
          $VCPKG_INSTALLATION_ROOT/vcpkg.exe install --triplet=x64-windows-static-md xxhash zstd openssl openssl-windows
          cd $VCPKG_INSTALLATION_ROOT/installed/x64-windows-static-md/lib
          cp zstd_static.lib zstd.lib
      # Runs a set of commands using the runners shell
      - name: Build pijul
        shell: bash
        run: |
          export VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT
          export LIB=$VCPKG_ROOT/installed/x64-windows-static-md/lib
          export OPENSSL_DIR=$VCPKG_ROOT/installed/x64-windows-static-md
          cargo install pijul --version $GITHUB_REF --root .
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: bin/pijul.exe
          tag: ${{ github.ref }}
